language: ruby

rvm:
- 2.4.4
- 2.3.4
- 2.6.0
- 2.5.1


env:
  global:
    - CC_TEST_REPORTER_ID=e6e10c7cc9bb01d1c2f3850c7ac5e7168af3e04d32193d11a1b977763f529847

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: bundle exec rspec spec --tag '~integration'

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

before_install: gem install bundler

cache: bundler

sudo: false

services:
  - docker

deploy:
  - provider: rubygems
    api_key:
      secure: YCC4KmUL1dzcpNq2QzZGl+favvFqfX5o2q1zcxIhmMCi53kxjjy7cjYw8xWacDtKKiS0dVDdZ6PckxoIK97qlMpBRupxvhvLUOAAhYfumuIr4tGP5vptaXG3hGKgc39wIs7tlbc8JWEehsZ2kBTE9nms4+Fu9e8+WGslN70OUFw=
    gem: aws_security_viz
    on:
      repo: anaynayak/aws-security-viz
      branch: master
  - provider: script
    script: rake docker:push
    on:
      branch: master