#!/usr/bin/env ruby

require 'aws_security_viz'
require 'trollop'

opts = Trollop::options do
  opt :access_key, 'AWS access key', :type => :string
  opt :secret_key, 'AWS secret key', :type => :string
  opt :region, 'AWS region to query', :default => 'us-east-1', :type => :string
  opt :source_file, 'JSON source file containing security groups', :type => :string
  opt :filename, 'Output file name', :type => :string, :default => 'aws-security-viz.png'
  opt :color, 'Colored node edges', :default => false
end
if opts[:source_file].nil?
  Trollop::die :access_key, 'is required' if opts[:access_key].nil?
  Trollop::die :secret_key, 'is required' if opts[:secret_key].nil?
end

VisualizeAws.new(AwsConfig.load, opts).unleash(opts[:filename])


