name: Ruby

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 * * SAT'

jobs:
  test:
    runs-on: ${{matrix.os}}-latest
    strategy:
      matrix:
        os:
          - ubuntu
          - macos

        ruby:
          - 3.1
          - 3.2
          - 3.3
          - 3.4

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rspec spec --tag '~integration'

